## Understanding Numpy

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import time

#check Numpy version
print(f"Numpy Version: {np.__version__}" )

#display settings for cleaner output 
np.set_printoptions(precision=3, suppress=True)

Numpy Version: 2.3.2


Creating Numpy Arrays

In [ ]:
# creating arrays from python lists
# 1D array: A simple sequence of numbers

arr1d =np.array([1,2,3,4,5]) 

#2D array: Think of this as a matrix or table with rows and columns 

arr2d = np.array([[1,2,3],
                  [4,5,6]])

#3D array: like a stack of 2d arrays - useful for images, time series, etc 
arr3d = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])

print("1D array: ", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)


creating Special Arrays in Numpy 

In [29]:
#creating arrays filled wih zeros - useful for initialising arrays 
#shape(3,4) mean 3 rows and 4 columns
zero = np.zeros((3,4))

#creating arrays filled with ones - often used as starting points 
ones = np.ones((2,3,4))         #3D ARRAy: 2 LAYERS,3 ROWS , 4 columns

#Empty array - faster than zeros/ones bu contains values 
#use when you will immediately fill the array with real data 
empty = np.empty((2,2))

print("zeros array (3x4):\n",zero)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n",empty)

zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0.25 0.5 ]
 [0.75 1.  ]]


`zero()` and `ones()` are memory efficient ways to create arrays of specific sizes. `empty()` is fastest but contains garbage values, so only use it when you'll immediately overwrite the contents.

In [ ]:
#Range arrays - like pythons range() but more powerful 
range_arr = np.arange(0,10,2)  #Start, stop, step:[0,2,4,6,8]
print("Range array", range_arr)

#Linearly spaced arrays - divide a range into equal parts
#from  0 to 1 with exactly 5 points (inclubing endpoints)
linspace_arr = np.linspace(0,1,5)
print("Logspace array: ",linspace_arr)

#logarithmically spaced arrays - useful for scientific data 
#from 10^0 to 10^2 (1 to 100) with 5 points 
logspace_arr = np.logspace(0,2,5)
print("Logspace array:", logspace_arr)

Range array [0 2 4 6 8]
Logspace array:  [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#identity matrix - diagonal of ones, zeros elsewhere 
#Essential for linear algebra operations 
identity = np.eye(4)         #4x4 identiti matrix 
#Diagonal matrix - put values on the diagonal 
diagonal = np.diag([1,2,3,4])

#Array filled with specific value 
full_arr = np.full((3,3),7)          #3x3 array filled with 7

print("Identity matrix:\n", identity)
print("Diagonal m,atrix:\n", diagonal)
print("full array (filled with 7):\n", full_arr)

Diagonal matrices are useful for scaling operations 

Numpy Data Types(dtypes)
    understanding data types is crutial for memory efficiency and numerical precision

In [ ]:
#Explicit data types - control memory usage and precision 
int_arr = np.array([1,2,3],dtype=np.int32) #32-bit  integers
float_arr = np.array([1,2,3],dtype=np.float64) #64-bit floats (double precision)
bool_arr = np.array([True,False,True],dtype=np.bool_) #Boolean values 

#Type conversion - change dtypes of existing array 
converted = int_arr.astype(np.float32) #convert to 32-bit float
print("Integer array dtype:",int_arr.dtype)
print("float array dtype:",float_arr.dtype)
print("boolean array dtype:",bool_arr.dtype)
print("converted array dtype:",converted.dtype)

#Mmory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")