## Understanding Numpy

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import time


#check Numpy version
print(f"Numpy Version: {np.__version__}" )

#display settings for cleaner output 
np.set_printoptions(precision=3, suppress=True)

Numpy Version: 2.3.2


Creating Numpy Arrays

In [3]:
# creating arrays from python lists
# 1D array: A simple sequence of numbers

arr1d =np.array([1,2,3,4,5]) 

#2D array: Think of this as a matrix or table with rows and columns 

arr2d = np.array([[1,2,3],
                  [4,5,6]])

#3D array: like a stack of 2d arrays - useful for images, time series, etc 
arr3d = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])

print("1D array: ", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)


1D array:  [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


creating Special Arrays in Numpy 

In [29]:
#creating arrays filled wih zeros - useful for initialising arrays 
#shape(3,4) mean 3 rows and 4 columns
zero = np.zeros((3,4))

#creating arrays filled with ones - often used as starting points 
ones = np.ones((2,3,4))         #3D ARRAy: 2 LAYERS,3 ROWS , 4 columns

#Empty array - faster than zeros/ones bu contains values 
#use when you will immediately fill the array with real data 
empty = np.empty((2,2))

print("zeros array (3x4):\n",zero)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n",empty)

zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0.25 0.5 ]
 [0.75 1.  ]]


`zero()` and `ones()` are memory efficient ways to create arrays of specific sizes. `empty()` is fastest but contains garbage values, so only use it when you'll immediately overwrite the contents.

In [ ]:
#Range arrays - like pythons range() but more powerful 
range_arr = np.arange(0,10,2)  #Start, stop, step:[0,2,4,6,8]
print("Range array", range_arr)

#Linearly spaced arrays - divide a range into equal parts
#from  0 to 1 with exactly 5 points (inclubing endpoints)
linspace_arr = np.linspace(0,1,5)
print("Logspace array: ",linspace_arr)

#logarithmically spaced arrays - useful for scientific data 
#from 10^0 to 10^2 (1 to 100) with 5 points 
logspace_arr = np.logspace(0,2,5)
print("Logspace array:", logspace_arr)

Range array [0 2 4 6 8]
Logspace array:  [0.   0.25 0.5  0.75 1.  ]


In [ ]:
#identity matrix - diagonal of ones, zeros elsewhere 
#Essential for linear algebra operations 
identity = np.eye(4)         #4x4 identiti matrix 
#Diagonal matrix - put values on the diagonal 
diagonal = np.diag([1,2,3,4])

#Array filled with specific value 
full_arr = np.full((3,3),7)          #3x3 array filled with 7

print("Identity matrix:\n", identity)
print("Diagonal m,atrix:\n", diagonal)
print("full array (filled with 7):\n", full_arr)

Diagonal matrices are useful for scaling operations 

Numpy Data Types(dtypes)
    understanding data types is crutial for memory efficiency and numerical precision

In [ ]:
#Explicit data types - control memory usage and precision 
int_arr = np.array([1,2,3],dtype=np.int32) #32-bit  integers
float_arr = np.array([1,2,3],dtype=np.float64) #64-bit floats (double precision)
bool_arr = np.array([True,False,True],dtype=np.bool_) #Boolean values 

#Type conversion - change dtypes of existing array 
converted = int_arr.astype(np.float32) #convert to 32-bit float
print("Integer array dtype:",int_arr.dtype)
print("float array dtype:",float_arr.dtype)
print("boolean array dtype:",bool_arr.dtype)
print("converted array dtype:",converted.dtype)

#Mmory usage comparison
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Arrray properties & Attributes 
    # Understanding array properties helps you work effectively with data and debug issue 

In [ ]:
# Create a sample 3D array for demonstration
# Think of this as 3 layers, each with 4 rows and 5 columns
arr= np.random.randn(3,4,5)

#shape:the dimension of the array (layers,row,columns)
print("shape:",arr.shape)

#size: Total number of elements(3x4x5 =60)
print("size:",arr.size)

#Ndim:number of dimensions(3Din this case )
print("ndim: ",arr.ndim)

#dtype:Data type of elements
print("Dtype: ",arr.dtype)

#itemsize: memory size of each element in bytes 
print("Itemsize: ",arr.itemsize)  #8 bytes for float

Array indexing and slicing 

Basic indexing - Accessing Individual Elements 

In [6]:
#1D array indexing - similar to python lists
arr1d= np.array([10,20,30,40,50]) 

print("first element: ",arr1d[0])       #indexing 0: 10
print("Last element:",arr1d[-1])        #Negative indexing:50 
print("slice [1:4]: ", arr1d[1:4])         #Elements 1,2,3: [20,30,40]
print("Every 2nd element: ",arr1d[::2])     #step of 2 [10,30,50]

first element:  10
Last element: 50
slice [1:4]:  [20 30 40]
Every 2nd element:  [10 30 50]


negative indices count from the end (-1 is last element)

In [8]:
#2D array indexing - row and column access 
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

#Acess specific element: [row,column]

print("Element at row 1, column 2:", arr2d[1, 2])        # 7

#access entire rows or colums 
print("first row: ",arr2d[0,:])     #all columns of row 0
print("second column:", arr2d[:,1])    #all rows of column 1

#subarray slicing: [row_start:rowend,col_start:col_end]
print("subarray (rows 1-2, col 1-2:):\n", arr2d[1:3,1:3])


Element at row 1, column 2: 7
first row:  [1 2 3 4]
second column: [ 2  6 10]
subarray (rows 1-2, col 1-2:):
 [[ 6  7]
 [10 11]]


The comma separates dimensions. : means "all elements along this dimension". Slicing creates views of the original data when possible, not copies.

**Advanced Indexing - Powerful Selection Methods**

In [ ]:
#fancy indexing - use arrays of indices to select elements 
arr = np.array([10,20,30,40,50])
indices = np.array([0,2,4])  #select elements at positions 0,2,4
print("fancy indexing:", arr[indices])      

#this ia much more flexible than simple slicing 
random_indices = np.array([4,1,3,1]) #cn repeat and reorder 
print("random order:",arr[random_indices])

Fancy indexing lets you select elements in any order, repeat elements, and select non-contiguous elements. Very useful for data sampling and reordering.

In [ ]:
#2d fancy indexing - select specific row/column combinations
arr2d = np.arange(12).reshape(3,4)  #3x4 array: [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
print("Original 2D array:\n",arr2d)

#select elements at (row,col) pairs:(0,1) and (2,3)
rows = np.array([0,2])
cols =np.array([1,3])
print("Elements at (0,1) and (2,3):", arr2d[rows, cols])

Original 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
