In [1]:
import numpy as np
import random

#check Numpy version
print(f"Numpy Version: {np.__version__}" )

#display settings for cleaner output 
np.set_printoptions(precision=3, suppress=True)

Numpy Version: 2.3.2


QUESTION 1

**Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.**

In [5]:
arr= np.random.randint(50,size=(6,6))
print(arr)

[[48 35 12 42 10  6]
 [ 9 43  6 10 38 44]
 [ 9 17 11 44 40  7]
 [12 44 17 19 41 45]
 [13 14 39 33 40 14]
 [45 33 42  2  0  6]]


Question 2

In [ ]:
print("first 2 rows: ", arr[:2])
print("last three colums: ", arr[:,3:])
print ("even numbers: ", arr[arr % 2 == 0])

first 2 rows:  [[48 35 12 42 10  6]
 [ 9 43  6 10 38 44]]
last three colums:  [[42 10  6]
 [10 38 44]
 [44 40  7]
 [19 41 45]
 [33 40 14]
 [ 2  0  6]]


Question 3

In [13]:
reshaped_array3d = arr.reshape(3,2,6)
print("The redhaped array is", reshaped_array3d)

flatreshaped= reshaped_array3d.flatten()
print("the flattened reshaped array", flatreshaped)

The redhaped array is [[[48 35 12 42 10  6]
  [ 9 43  6 10 38 44]]

 [[ 9 17 11 44 40  7]
  [12 44 17 19 41 45]]

 [[13 14 39 33 40 14]
  [45 33 42  2  0  6]]]
the flattened reshaped array [48 35 12 42 10  6  9 43  6 10 38 44  9 17 11 44 40  7 12 44 17 19 41 45
 13 14 39 33 40 14 45 33 42  2  0  6]


Question 4

In [ ]:
identity_matrix = np.eye(4)
print(identity_matrix)
diagonal_array = np.arange(10,40,10)
diagonal_matrix  = np.array(diagonal_array)
np.fill_diagonal(identity_matrix,diagonal_array)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 10.]]


Question 5

In [ ]:
arr1 = np.random.randint(np.arange(1,10),size=(3,4))
print (arr1)